In [2]:
import numpy as np
import pandas as pd

## What's the version of NumPy that you installed? 

In [3]:
np.__version__

'1.22.3'

## Getting the data 

In [4]:
!wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv

--2022-09-11 11:01:51--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1475504 (1,4M) [text/plain]
Saving to: 'data.csv.1'

     0K .......... .......... .......... .......... ..........  3% 1,04M 1s
    50K .......... .......... .......... .......... ..........  6% 3,97M 1s
   100K .......... .......... .......... .......... .......... 10% 1,59M 1s
   150K .......... .......... .......... .......... .......... 13% 5,79M 1s
   200K .......... .......... .......... .......... .......... 17% 6,22M 1s
   250K .......... .......... .......... .......... .......... 20% 2,41M 0s
   300K .......... .......... .......... .......... .......... 24% 6,36M 0s
   350K 

In [5]:
df_car = pd.read_csv("data.csv")

## How many records are in the dataset?

In [6]:
df_car.shape

(11914, 16)

11914

## Who are the most popular car manufacturers (top-3) according to the dataset?

In [7]:
df_car.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [11]:
df_car.groupby(['Make'])['Make'].count().sort_values()

Make
Genesis             3
Spyker              3
Bugatti             3
Alfa Romeo          5
McLaren             5
Maybach            16
HUMMER             17
Tesla              18
Lotus              29
Rolls-Royce        31
Lamborghini        52
Maserati           58
Scion              60
FIAT               62
Ferrari            69
Bentley            74
Plymouth           82
Aston Martin       93
Saab              111
Porsche           136
Land Rover        143
Oldsmobile        150
Lincoln           164
Pontiac           186
Chrysler          187
Buick             196
Lexus             202
Mitsubishi        213
Kia               231
Acura             252
Subaru            256
Volvo             281
Hyundai           303
Audi              328
Infiniti          330
BMW               334
Suzuki            351
Mercedes-Benz     353
Cadillac          397
Mazda             423
Honda             449
GMC               515
Nissan            558
Dodge             626
Toyota            746
Volks

Chevrolet, Ford, Volkswagen

## What's the number of unique Audi car models in the dataset?

In [12]:
df_car[df_car["Make"] == "Audi"]["Model"].drop_duplicates().count()

34

34 

## How many columns in the dataset have missing values?

In [13]:
df_car.isna().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [14]:
df_car.isna().sum()[lambda x: x > 0].count()

5

5

## Question 6

* Find the median value of "Engine Cylinders" column in the dataset.
* Next, calculate the most frequent value of the same "Engine Cylinders".
* Use the `fillna` method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.
* Now, calculate the median value of "Engine Cylinders" once again.

Has it changed?

In [15]:
df_car["Engine Cylinders"].median()

6.0

In [16]:
mfv = df_car["Engine Cylinders"].mode()
float(mfv)

4.0

In [17]:
df_car["Engine Cylinders"] = df_car["Engine Cylinders"].fillna(mfv.iloc[0])

In [18]:
df_car["Engine Cylinders"].median()

6.0

No

## Question 7

* Select all the "Lotus" cars from the dataset.
* Select only columns "Engine HP", "Engine Cylinders".
* Now drop all duplicated rows using `drop_duplicates` method (you should get a dataframe with 9 rows).
* Get the underlying NumPy array. Let's call it `X`.
* Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
* Invert `XTX`.
* Create an array `y` with values `[1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]`.
* Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
* What's the value of the first element of `w`?

In [19]:
lotus = df_car[df_car["Make"] == "Lotus"][["Engine HP", "Engine Cylinders"]]

In [20]:
display(lotus.head())
lotus.shape

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3914      189.0               4.0
3915      189.0               4.0
3916      218.0               4.0

(29, 2)

In [21]:
lotus = lotus.drop_duplicates()

In [22]:
lotus.shape

(9, 2)

In [23]:
X = lotus.to_numpy()

In [24]:
XTX = X.T.dot(X)
display(XTX)

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [25]:
XTX = np.linalg.inv(XTX)
display(XTX)

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [26]:
y = [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]

In [27]:
w = XTX.dot(X.T).dot(y)
display(w)

array([  4.59494481, -63.56432501])

In [28]:
w[0]

4.594944810094551